"""String templates for the 4-section CLI report."""

from __future__ import annotations

IMPACT_LABELS: dict[int, str] = {
    1: "Negligible",
    2: "Low",
    3: "Moderate",
    4: "High",
    5: "Critical",
}

IMPACT_CRITERIA: dict[int, str] = {
    1: "No economic loss. No customer impact. Internal only.",
    2: "Minor economic loss (<$1,000). Easily reversible. No customer notification required.",
    3: "Meaningful economic loss ($1,000-$25,000). Customer impact possible. Reversible with effort.",
    4: "Significant economic loss ($25,000-$250,000). Customer impact confirmed. Partial irreversibility.",
    5: "Severe economic loss (>$250,000). Regulatory exposure. Reputational damage. Irreversible consequences.",
}

REPORT_HEADER = """\
# Agent Incident Report

**{incident_id}** | Generated {generated_at} | Classification: {status}

---"""

EXECUTIVE_SUMMARY = """\
## 1. Executive Summary

On {incident_date}, {agent_desc} executed {trace_count} tool call(s).
{constraint_summary}
The incident is classified as **{fault_class}** with an impact score of **{impact_score}/5**
({impact_label}).{loss_sentence}"""

AUTO_CLASSIFY_NOTE = """
> **Note:** fault_class was automatically classified by the reference rules engine
> (confidence: {confidence:.2f}). This classification is advisory. Review and confirm
> at agentincident.com."""

TIMELINE_HEADER = """\
## 2. Timeline

| Time | Tool | Details |
|------|------|---------|"""

TIMELINE_ROW = "| {ts} | `{tool}` | {details} |"

FAULT_CLASSIFICATION_HEADER = """\
## 3. Fault Classification

| Field | Value |
|-------|-------|
| fault_class | **{fault_class}** |
| impact_score | {impact_score} / 5 ({impact_label}) |
| loss_amount_usd | {loss_display} |"""

CLASSIFICATION_EXTRA = """\
| confidence | {confidence} |
| classifier | {classifier} |"""

IMPACT_ASSESSMENT_HEADER = """\
## 4. Impact Assessment

**{impact_label}** — {impact_criteria}"""

LOSS_BREAKDOWN_HEADER = """
| Category | Amount |
|----------|--------|"""

LOSS_BREAKDOWN_ROW = "| {category} | {amount} |"

LOSS_BREAKDOWN_TOTAL = "| **Total estimated** | **${total:,.2f}** |"

REPORT_FOOTER = """
---

*Generated by [agentincident](https://github.com/agentincident/agentincident) (open-source)*
*Full 11-section reports with root cause analysis, remediation plans, and verification: [agentincident.com](https://agentincident.com)*"""
